version: "3"
services:
  api:
    build:
      dockerfile: backend.Dockerfile
      context: .
    expose:
      - 3000
    ports:
      - 3000:3000
  nginx:
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: .
    ports:
      - "80:80"
    depends_on:
      - client
      - api
  client:
    build:
      dockerfile: frontend.Dockerfile
      context: .
