name: Deploy web recipes app
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: git branch -r
      - run: npx nx show projects --affected --base=main~1 --head=main
