name: Deploy web recipes app
on: [push, workflow_dispatch]
jobs:
  Check-Affected-Apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 origin main
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: |
          APPS=`npx nx show projects --affected`
          if ! grep -q "$APPS" <<< web; then
            exit 1
          fi
      - run:
          echo "OK"

